/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as DashRouteImport } from './routes/dash'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as DashIndexRouteImport } from './routes/dash.index'
import { Route as PainelSuporteRouteImport } from './routes/painel.suporte'
import { Route as PainelPraticantesRouteImport } from './routes/painel.praticantes'
import { Route as PainelCreditosRouteImport } from './routes/painel.creditos'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel.configuracoes'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as MinhaContaPerfilRouteImport } from './routes/minha-conta.perfil'
import { Route as MinhaContaGraduacoesRouteImport } from './routes/minha-conta.graduacoes'
import { Route as MinhaContaCarteirinhaRouteImport } from './routes/minha-conta.carteirinha'
import { Route as DashSuporteRouteImport } from './routes/dash.suporte'
import { Route as DashOrganizacoesRouteImport } from './routes/dash.organizacoes'
import { Route as DashModelosRouteImport } from './routes/dash.modelos'
import { Route as DashGraduacoesRouteImport } from './routes/dash.graduacoes'
import { Route as DashFinanceiroRouteImport } from './routes/dash.financeiro'
import { Route as DashContatosRouteImport } from './routes/dash.contatos'
import { Route as DashAuditoriaRouteImport } from './routes/dash.auditoria'
import { Route as DashAtletasRouteImport } from './routes/dash.atletas'
import { Route as PainelPraticantesNovoRouteImport } from './routes/painel.praticantes.novo'
import { Route as PainelConquistasNovaRouteImport } from './routes/painel.conquistas.nova'
import { Route as DashOrganizacoesIdRouteImport } from './routes/dash.organizacoes.$id'
import { Route as DashAtletasIdRouteImport } from './routes/dash.atletas.$id'
import { Route as PainelPraticantesIdEditarRouteImport } from './routes/painel.praticantes.$id.editar'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const PainelSuporteRoute = PainelSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPraticantesRoute = PainelPraticantesRouteImport.update({
  id: '/praticantes',
  path: '/praticantes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCreditosRoute = PainelCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaPerfilRoute = MinhaContaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaGraduacoesRoute = MinhaContaGraduacoesRouteImport.update({
  id: '/graduacoes',
  path: '/graduacoes',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaCarteirinhaRoute = MinhaContaCarteirinhaRouteImport.update({
  id: '/carteirinha',
  path: '/carteirinha',
  getParentRoute: () => MinhaContaRoute,
} as any)
const DashSuporteRoute = DashSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => DashRoute,
} as any)
const DashOrganizacoesRoute = DashOrganizacoesRouteImport.update({
  id: '/organizacoes',
  path: '/organizacoes',
  getParentRoute: () => DashRoute,
} as any)
const DashModelosRoute = DashModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => DashRoute,
} as any)
const DashGraduacoesRoute = DashGraduacoesRouteImport.update({
  id: '/graduacoes',
  path: '/graduacoes',
  getParentRoute: () => DashRoute,
} as any)
const DashFinanceiroRoute = DashFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashRoute,
} as any)
const DashContatosRoute = DashContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => DashRoute,
} as any)
const DashAuditoriaRoute = DashAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => DashRoute,
} as any)
const DashAtletasRoute = DashAtletasRouteImport.update({
  id: '/atletas',
  path: '/atletas',
  getParentRoute: () => DashRoute,
} as any)
const PainelPraticantesNovoRoute = PainelPraticantesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => PainelPraticantesRoute,
} as any)
const PainelConquistasNovaRoute = PainelConquistasNovaRouteImport.update({
  id: '/conquistas/nova',
  path: '/conquistas/nova',
  getParentRoute: () => PainelRoute,
} as any)
const DashOrganizacoesIdRoute = DashOrganizacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashOrganizacoesRoute,
} as any)
const DashAtletasIdRoute = DashAtletasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashAtletasRoute,
} as any)
const PainelPraticantesIdEditarRoute =
  PainelPraticantesIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => PainelPraticantesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dash': typeof DashRouteWithChildren
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/verificar': typeof VerificarRoute
  '/dash/atletas': typeof DashAtletasRouteWithChildren
  '/dash/auditoria': typeof DashAuditoriaRoute
  '/dash/contatos': typeof DashContatosRoute
  '/dash/financeiro': typeof DashFinanceiroRoute
  '/dash/graduacoes': typeof DashGraduacoesRoute
  '/dash/modelos': typeof DashModelosRoute
  '/dash/organizacoes': typeof DashOrganizacoesRouteWithChildren
  '/dash/suporte': typeof DashSuporteRoute
  '/minha-conta/carteirinha': typeof MinhaContaCarteirinhaRoute
  '/minha-conta/graduacoes': typeof MinhaContaGraduacoesRoute
  '/minha-conta/perfil': typeof MinhaContaPerfilRoute
  '/p/$id': typeof PIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/creditos': typeof PainelCreditosRoute
  '/painel/praticantes': typeof PainelPraticantesRouteWithChildren
  '/painel/suporte': typeof PainelSuporteRoute
  '/dash/': typeof DashIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/dash/atletas/$id': typeof DashAtletasIdRoute
  '/dash/organizacoes/$id': typeof DashOrganizacoesIdRoute
  '/painel/conquistas/nova': typeof PainelConquistasNovaRoute
  '/painel/praticantes/novo': typeof PainelPraticantesNovoRoute
  '/painel/praticantes/$id/editar': typeof PainelPraticantesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/verificar': typeof VerificarRoute
  '/dash/atletas': typeof DashAtletasRouteWithChildren
  '/dash/auditoria': typeof DashAuditoriaRoute
  '/dash/contatos': typeof DashContatosRoute
  '/dash/financeiro': typeof DashFinanceiroRoute
  '/dash/graduacoes': typeof DashGraduacoesRoute
  '/dash/modelos': typeof DashModelosRoute
  '/dash/organizacoes': typeof DashOrganizacoesRouteWithChildren
  '/dash/suporte': typeof DashSuporteRoute
  '/minha-conta/carteirinha': typeof MinhaContaCarteirinhaRoute
  '/minha-conta/graduacoes': typeof MinhaContaGraduacoesRoute
  '/minha-conta/perfil': typeof MinhaContaPerfilRoute
  '/p/$id': typeof PIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/creditos': typeof PainelCreditosRoute
  '/painel/praticantes': typeof PainelPraticantesRouteWithChildren
  '/painel/suporte': typeof PainelSuporteRoute
  '/dash': typeof DashIndexRoute
  '/painel': typeof PainelIndexRoute
  '/dash/atletas/$id': typeof DashAtletasIdRoute
  '/dash/organizacoes/$id': typeof DashOrganizacoesIdRoute
  '/painel/conquistas/nova': typeof PainelConquistasNovaRoute
  '/painel/praticantes/novo': typeof PainelPraticantesNovoRoute
  '/painel/praticantes/$id/editar': typeof PainelPraticantesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dash': typeof DashRouteWithChildren
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/painel': typeof PainelRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/verificar': typeof VerificarRoute
  '/dash/atletas': typeof DashAtletasRouteWithChildren
  '/dash/auditoria': typeof DashAuditoriaRoute
  '/dash/contatos': typeof DashContatosRoute
  '/dash/financeiro': typeof DashFinanceiroRoute
  '/dash/graduacoes': typeof DashGraduacoesRoute
  '/dash/modelos': typeof DashModelosRoute
  '/dash/organizacoes': typeof DashOrganizacoesRouteWithChildren
  '/dash/suporte': typeof DashSuporteRoute
  '/minha-conta/carteirinha': typeof MinhaContaCarteirinhaRoute
  '/minha-conta/graduacoes': typeof MinhaContaGraduacoesRoute
  '/minha-conta/perfil': typeof MinhaContaPerfilRoute
  '/p/$id': typeof PIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/painel/creditos': typeof PainelCreditosRoute
  '/painel/praticantes': typeof PainelPraticantesRouteWithChildren
  '/painel/suporte': typeof PainelSuporteRoute
  '/dash/': typeof DashIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/dash/atletas/$id': typeof DashAtletasIdRoute
  '/dash/organizacoes/$id': typeof DashOrganizacoesIdRoute
  '/painel/conquistas/nova': typeof PainelConquistasNovaRoute
  '/painel/praticantes/novo': typeof PainelPraticantesNovoRoute
  '/painel/praticantes/$id/editar': typeof PainelPraticantesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/dash'
    | '/minha-conta'
    | '/painel'
    | '/privacidade'
    | '/recuperar-senha'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/verificar'
    | '/dash/atletas'
    | '/dash/auditoria'
    | '/dash/contatos'
    | '/dash/financeiro'
    | '/dash/graduacoes'
    | '/dash/modelos'
    | '/dash/organizacoes'
    | '/dash/suporte'
    | '/minha-conta/carteirinha'
    | '/minha-conta/graduacoes'
    | '/minha-conta/perfil'
    | '/p/$id'
    | '/painel/configuracoes'
    | '/painel/creditos'
    | '/painel/praticantes'
    | '/painel/suporte'
    | '/dash/'
    | '/painel/'
    | '/dash/atletas/$id'
    | '/dash/organizacoes/$id'
    | '/painel/conquistas/nova'
    | '/painel/praticantes/novo'
    | '/painel/praticantes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/minha-conta'
    | '/privacidade'
    | '/recuperar-senha'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/verificar'
    | '/dash/atletas'
    | '/dash/auditoria'
    | '/dash/contatos'
    | '/dash/financeiro'
    | '/dash/graduacoes'
    | '/dash/modelos'
    | '/dash/organizacoes'
    | '/dash/suporte'
    | '/minha-conta/carteirinha'
    | '/minha-conta/graduacoes'
    | '/minha-conta/perfil'
    | '/p/$id'
    | '/painel/configuracoes'
    | '/painel/creditos'
    | '/painel/praticantes'
    | '/painel/suporte'
    | '/dash'
    | '/painel'
    | '/dash/atletas/$id'
    | '/dash/organizacoes/$id'
    | '/painel/conquistas/nova'
    | '/painel/praticantes/novo'
    | '/painel/praticantes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/contato'
    | '/dash'
    | '/minha-conta'
    | '/painel'
    | '/privacidade'
    | '/recuperar-senha'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/verificar'
    | '/dash/atletas'
    | '/dash/auditoria'
    | '/dash/contatos'
    | '/dash/financeiro'
    | '/dash/graduacoes'
    | '/dash/modelos'
    | '/dash/organizacoes'
    | '/dash/suporte'
    | '/minha-conta/carteirinha'
    | '/minha-conta/graduacoes'
    | '/minha-conta/perfil'
    | '/p/$id'
    | '/painel/configuracoes'
    | '/painel/creditos'
    | '/painel/praticantes'
    | '/painel/suporte'
    | '/dash/'
    | '/painel/'
    | '/dash/atletas/$id'
    | '/dash/organizacoes/$id'
    | '/painel/conquistas/nova'
    | '/painel/praticantes/novo'
    | '/painel/praticantes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  DashRoute: typeof DashRouteWithChildren
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  PainelRoute: typeof PainelRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  VerificarRoute: typeof VerificarRoute
  PIdRoute: typeof PIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/painel/suporte': {
      id: '/painel/suporte'
      path: '/suporte'
      fullPath: '/painel/suporte'
      preLoaderRoute: typeof PainelSuporteRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/praticantes': {
      id: '/painel/praticantes'
      path: '/praticantes'
      fullPath: '/painel/praticantes'
      preLoaderRoute: typeof PainelPraticantesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/creditos': {
      id: '/painel/creditos'
      path: '/creditos'
      fullPath: '/painel/creditos'
      preLoaderRoute: typeof PainelCreditosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/perfil': {
      id: '/minha-conta/perfil'
      path: '/perfil'
      fullPath: '/minha-conta/perfil'
      preLoaderRoute: typeof MinhaContaPerfilRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/graduacoes': {
      id: '/minha-conta/graduacoes'
      path: '/graduacoes'
      fullPath: '/minha-conta/graduacoes'
      preLoaderRoute: typeof MinhaContaGraduacoesRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/carteirinha': {
      id: '/minha-conta/carteirinha'
      path: '/carteirinha'
      fullPath: '/minha-conta/carteirinha'
      preLoaderRoute: typeof MinhaContaCarteirinhaRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/dash/suporte': {
      id: '/dash/suporte'
      path: '/suporte'
      fullPath: '/dash/suporte'
      preLoaderRoute: typeof DashSuporteRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/organizacoes': {
      id: '/dash/organizacoes'
      path: '/organizacoes'
      fullPath: '/dash/organizacoes'
      preLoaderRoute: typeof DashOrganizacoesRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/modelos': {
      id: '/dash/modelos'
      path: '/modelos'
      fullPath: '/dash/modelos'
      preLoaderRoute: typeof DashModelosRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/graduacoes': {
      id: '/dash/graduacoes'
      path: '/graduacoes'
      fullPath: '/dash/graduacoes'
      preLoaderRoute: typeof DashGraduacoesRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/financeiro': {
      id: '/dash/financeiro'
      path: '/financeiro'
      fullPath: '/dash/financeiro'
      preLoaderRoute: typeof DashFinanceiroRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/contatos': {
      id: '/dash/contatos'
      path: '/contatos'
      fullPath: '/dash/contatos'
      preLoaderRoute: typeof DashContatosRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/auditoria': {
      id: '/dash/auditoria'
      path: '/auditoria'
      fullPath: '/dash/auditoria'
      preLoaderRoute: typeof DashAuditoriaRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/atletas': {
      id: '/dash/atletas'
      path: '/atletas'
      fullPath: '/dash/atletas'
      preLoaderRoute: typeof DashAtletasRouteImport
      parentRoute: typeof DashRoute
    }
    '/painel/praticantes/novo': {
      id: '/painel/praticantes/novo'
      path: '/novo'
      fullPath: '/painel/praticantes/novo'
      preLoaderRoute: typeof PainelPraticantesNovoRouteImport
      parentRoute: typeof PainelPraticantesRoute
    }
    '/painel/conquistas/nova': {
      id: '/painel/conquistas/nova'
      path: '/conquistas/nova'
      fullPath: '/painel/conquistas/nova'
      preLoaderRoute: typeof PainelConquistasNovaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/dash/organizacoes/$id': {
      id: '/dash/organizacoes/$id'
      path: '/$id'
      fullPath: '/dash/organizacoes/$id'
      preLoaderRoute: typeof DashOrganizacoesIdRouteImport
      parentRoute: typeof DashOrganizacoesRoute
    }
    '/dash/atletas/$id': {
      id: '/dash/atletas/$id'
      path: '/$id'
      fullPath: '/dash/atletas/$id'
      preLoaderRoute: typeof DashAtletasIdRouteImport
      parentRoute: typeof DashAtletasRoute
    }
    '/painel/praticantes/$id/editar': {
      id: '/painel/praticantes/$id/editar'
      path: '/$id/editar'
      fullPath: '/painel/praticantes/$id/editar'
      preLoaderRoute: typeof PainelPraticantesIdEditarRouteImport
      parentRoute: typeof PainelPraticantesRoute
    }
  }
}

interface DashAtletasRouteChildren {
  DashAtletasIdRoute: typeof DashAtletasIdRoute
}

const DashAtletasRouteChildren: DashAtletasRouteChildren = {
  DashAtletasIdRoute: DashAtletasIdRoute,
}

const DashAtletasRouteWithChildren = DashAtletasRoute._addFileChildren(
  DashAtletasRouteChildren,
)

interface DashOrganizacoesRouteChildren {
  DashOrganizacoesIdRoute: typeof DashOrganizacoesIdRoute
}

const DashOrganizacoesRouteChildren: DashOrganizacoesRouteChildren = {
  DashOrganizacoesIdRoute: DashOrganizacoesIdRoute,
}

const DashOrganizacoesRouteWithChildren =
  DashOrganizacoesRoute._addFileChildren(DashOrganizacoesRouteChildren)

interface DashRouteChildren {
  DashAtletasRoute: typeof DashAtletasRouteWithChildren
  DashAuditoriaRoute: typeof DashAuditoriaRoute
  DashContatosRoute: typeof DashContatosRoute
  DashFinanceiroRoute: typeof DashFinanceiroRoute
  DashGraduacoesRoute: typeof DashGraduacoesRoute
  DashModelosRoute: typeof DashModelosRoute
  DashOrganizacoesRoute: typeof DashOrganizacoesRouteWithChildren
  DashSuporteRoute: typeof DashSuporteRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAtletasRoute: DashAtletasRouteWithChildren,
  DashAuditoriaRoute: DashAuditoriaRoute,
  DashContatosRoute: DashContatosRoute,
  DashFinanceiroRoute: DashFinanceiroRoute,
  DashGraduacoesRoute: DashGraduacoesRoute,
  DashModelosRoute: DashModelosRoute,
  DashOrganizacoesRoute: DashOrganizacoesRouteWithChildren,
  DashSuporteRoute: DashSuporteRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

interface MinhaContaRouteChildren {
  MinhaContaCarteirinhaRoute: typeof MinhaContaCarteirinhaRoute
  MinhaContaGraduacoesRoute: typeof MinhaContaGraduacoesRoute
  MinhaContaPerfilRoute: typeof MinhaContaPerfilRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaCarteirinhaRoute: MinhaContaCarteirinhaRoute,
  MinhaContaGraduacoesRoute: MinhaContaGraduacoesRoute,
  MinhaContaPerfilRoute: MinhaContaPerfilRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

interface PainelPraticantesRouteChildren {
  PainelPraticantesNovoRoute: typeof PainelPraticantesNovoRoute
  PainelPraticantesIdEditarRoute: typeof PainelPraticantesIdEditarRoute
}

const PainelPraticantesRouteChildren: PainelPraticantesRouteChildren = {
  PainelPraticantesNovoRoute: PainelPraticantesNovoRoute,
  PainelPraticantesIdEditarRoute: PainelPraticantesIdEditarRoute,
}

const PainelPraticantesRouteWithChildren =
  PainelPraticantesRoute._addFileChildren(PainelPraticantesRouteChildren)

interface PainelRouteChildren {
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelCreditosRoute: typeof PainelCreditosRoute
  PainelPraticantesRoute: typeof PainelPraticantesRouteWithChildren
  PainelSuporteRoute: typeof PainelSuporteRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelConquistasNovaRoute: typeof PainelConquistasNovaRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelCreditosRoute: PainelCreditosRoute,
  PainelPraticantesRoute: PainelPraticantesRouteWithChildren,
  PainelSuporteRoute: PainelSuporteRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelConquistasNovaRoute: PainelConquistasNovaRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  DashRoute: DashRouteWithChildren,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  PainelRoute: PainelRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  VerificarRoute: VerificarRoute,
  PIdRoute: PIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
